config/routes.rb
Rails.application.routes.draw do
  get 'accounts/create'
  get 'accounts/show'
  get 'home/index'
  devise_for :views
  devise_for :users
  #root to: 'pages#dashboard'
  root to: "home#index"
  post 'account' => 'accounts#create', as: :user_account

  get 'verify/reference' => 'transactions#verify_transactions', as: :verify_transactions
  get 'user/transactions' => 'transactions#user_transaction', as: :user_transactions

  get 'pages/dashboard'
  get 'pages/icons'
  get 'pages/profile'
  get 'pages/tables'
  get 'pages/login'
  get 'pages/register'
  get 'pages/upgrade'
end

app/models/account.rb
class Account < ApplicationRecord


end

app/models/role.rb
class Role < ApplicationRecord
	  has_and_belongs_to_many :users,:join_table => :roles_users


end

app/models/song.rb
class Song < ApplicationRecord

  has_many :transactions

end

app/models/transaction.rb
class Transaction < ApplicationRecord

  belongs_to :users, optional: true
  belongs_to :songs, optional: true

  def song_name
  	Song.where(song_id: self.song_id)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #has_and_belongs_to_many :roles , :join_table => :roles_users
  has_many :transactions

  


end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  require 'httparty'

  skip_before_action :verify_authenticity_token, :only => [:create]

  def create
  	@user = current_user.id
  	bank_code = params[:bank_code]
  	account_number = params[:account_number]

  	#verify the account number
  	headers = { 
  		"Content-Type"  => "application/json",
  		"Authorization" => "Bearer sk_test_a18d989117519e3ac64b574291657d9b1f2031c2" 
		}

	verify_endpoint = 'https://api.paystack.co/bank/resolve?account_number='+account_number+'&bank_code='+bank_code
	logger.debug("Account verification endpoint is #{verify_endpoint}")
	@verify_response = HTTParty.get(verify_endpoint,:headers => headers)
    verify_data = JSON.parse(@verify_response.body)
    logger.debug("Verification Response is #{@verify_response.code}")
	if @verify_response.code == 200 && account_number.to_s == verify_data['data']['account_number']
			endpoint = 'https://api.paystack.co/subaccount'
		  	@response = HTTParty.post(endpoint,
		      :body => {    
		                :business_name => "Mavin Records",
		                :bank_code => "#{bank_code}",
		                :account_number => "#{account_number}",
		                :percentage_charge => 98}.to_json, 
		      :headers => headers)
			
			
		    user_data = JSON.parse(@response.body)
			logger.debug("#{user_data}")
			account = Account.new
			logger.debug("Account is #{account}")
			account.business_name = user_data['data']['business_name']
			account.account_number = user_data['data']['account_number']
			account.percentage_charge = user_data['data']['percentage_charge']
			account.settlement_bank = user_data['data']['settlement_bank']
			account.subaccount_code = user_data['data']['subaccount_code']
			account.is_verified = user_data['data']['is_verified']
			account.active = user_data['data']['active']
			account.createdat = user_data['data']['createdAt']
			account.updatedat = user_data['data']['updatedAt']
			account.user_id = @user
			account.currency = user_data['data']['currency']

			# set name value however you want to do that
			if account.save
				redirect_to(root_path, :notice => 'Account successfully created')
			end		
	end
	
    
	

  end

  def show
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:index]

  def index
  	   @user = current_user    
  	   @account_owner = @user.id
  	   @account = Account.find_by(user_id: current_user.id) 
	   #logger.debug("Account is #{@account.active}")
  	   @songs = Song.where(user_id: current_user.id)
	   @test_pub_key = "pk_test_e8b1026ad787f2ac2df0b50e54e222469f49a459"
  	   creator_account = Account.find_by(user_id: 6)
  	   @creator_subaccount = creator_account['subaccount_code'] if creator_account
  	   #@creator_subaccount = creator_account['subaccount_code'].to_s
  	   @txn_ref = SecureRandom.hex(10)
  	   @total_revenue = Transaction.where(status: 'Paid').sum(:platform_amount)
  	   @total_creator_payout = Transaction.where(status: 'Paid').sum(:creator_amount)
  	   @total_payment = Transaction.where(status: 'Paid').sum(:amount)
  	   #@transactions = Song.joins(:transactions)
  	   @transactions = Transaction.all
	   logger.debug("Total Transaction is #{@total_revenue.round}")
	   logger.debug("User ID is #{@account_owner}")


	   if @user.fan_role == true
			transaction = Transaction.new(:trxn_reference => @txn_ref, :amount => 450000, :payment_date => DateTime.now, :song_id => 1, :user_id => @account_owner, :status => 'Initiated')
			if transaction.save!
	   				logger.debug("I got here now with transaction #{transaction['trxn_reference']}")

			end
	   		
	   end





  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
   require 'httparty'
    
    skip_before_action :verify_authenticity_token, :only => [:verify_transactions]

	def verify_transactions
		txn_reference = params[:reference]
		headers = { 
  		"Content-Type"  => "application/json",
  		"Authorization" => "Bearer sk_test_a18d989117519e3ac64b574291657d9b1f2031c2" 
		}
		endpoint = "https://api.paystack.co/transaction/verify/#{txn_reference}"
    	logger.debug("Transaction endpoint send to paystack is #{endpoint}")
		@response = HTTParty.get(endpoint,:headers => headers)
    	verification_data = JSON.parse(@response.body)
    	logger.debug("Transaction data is #{verification_data}")
    	if @response.code == 200 && verification_data['data']['status'] == 'success' 
    		platform_amount = verification_data['data']['fees_split']['integration'].round(0)
    		creator_amount = verification_data['data']['fees_split']['subaccount'].round(0)
    		paystack_charge = verification_data['data']['fees_split']['paystack'].round(0)
    	    Transaction.where(:trxn_reference => txn_reference).update_all({:status => "Paid", :platform_amount => platform_amount, :creator_amount => creator_amount, :payment_provider_amount => paystack_charge})
			redirect_to(user_transactions_path, :notice => 'Transaction Successful')	
    	end

	end
	def user_transaction
		user_id = current_user.id
		@user_transactions = Transaction.where(user_id: user_id)
		logger.debug("Users Transactions are #{@user_transactions}")
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/accounts/create.html.erb</p>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>

app/views/home/index.html.erb
											
<div class="card">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col-8">
        <h3 class="mb-0">Welcome, <%= current_user.email %> </h3>
      </div>
      <div class="col-4 text-right">
	    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

      </div>
    </div>
  </div>
<% if current_user.creator_role? %>
	<div class="card">
	  <div class="card-header">
	    <div class="row align-items-center">
	      <div class="col-8">
	        <h3 class="mb-0">My Account </h3>
	      </div>
	      
	    </div>
	  </div>
	  <div class="card-body">
	      <h6 class="heading-small text-muted mb-4">User information</h6>
	      <div class="pl-lg-4">
	        <div class="row">
	          <div class="col-lg-6">
	            <div class="form-group">
	              <label class="form-control-label" for="input-email">Email address:</label> &nbsp;<%= current_user.email %><br>
	              <label class="form-control-label" for="input-first-name">First name:</label> &nbsp; Lucky <br>
	              <label class="form-control-label" for="input-last-name">Last name:</label> &nbsp; Jesse

	            </div>
	          </div>

	        </div>
	      </div>
	      <hr class="my-4" />
	      <!-- Address -->
	      <h6 class="heading-small text-muted mb-4">My Songs</h6>
	      <% if @songs.present? %>

		      	<table data-toggle="table" class="table table-responsive">
				    <thead>
				        <tr>
				            <th data-field="name" data-sortable="true">Name</th>
				            <th data-field="label" data-sortable="true">Label</th>
				            <th data-field="title" data-sortable="true">Title</th>
				            <th data-field="price" data-sortable="true">Price</th>
				            <th data-field="accept-job" data-sortable="true">Created Date</th>
				        </tr>
				     </thead>
		     		<tbody>
		     			<% @songs.each do |song| %>
				         <tr>
				             <td><%= song.artist%></td>
				             <td><%= song.label %></td>
				             <td><%= song.title %></td>
				             <td>N<%= song.price %></td>
				             <td><%= song.createdat.strftime("%d-%m-%Y")%></td>

				         </tr>
				        <% end %>
		    		</tbody>
		    	 </table>
		      <% end %>
	      <div class="pl-lg-4">
	      </div>
	      <hr class="my-4" />
	      <!-- Description -->
	      <h6 class="heading-small text-muted mb-4">Payment Information</h6>
	      <div>
	          <label class="form-control-label">Account Details</label>

	          <% if @account.present? %>

		      	<table data-toggle="table" class="table table-responsive">
				    <thead>
				        <tr>
				            <th data-field="date" data-sortable="true">Account Number</th>
				            <th data-field="deadline" data-sortable="true">Account Status</th>
				            <th data-field="accept-job" data-sortable="true">Bank Name</th>
				            <th data-field="accept-job" data-sortable="true">Created Date</th>
				        </tr>
				     </thead>
		     		<tbody>
				         <tr>
				             <td><%= @account.account_number%></td>
				             <td><%= @account.active == true ? 'Active' : 'Inactive' %></td>
				             <td><%= @account.settlement_bank%></td>
				             <td><%= @account.createdat.strftime("%d-%m-%Y")%></td>

				         </tr>
		    		</tbody>
		    	 </table>
		    	 <% else %>
		    	 	 <div class="pl-lg-4">
			        <div class="form-group">
			          <label class="form-control-label">Setup your account details to start receiving payments</label>
			          <button id="myBtn" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Add Account</button>          
			        </div>
			      </div>
		      <% end %>
	      </div>
	  </div>
	</div>
	<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
            	<form action="/account" method="post">
	  			  <h3>Add account details</h3>
				   	  <label>Select Bank:</label>
					  <select name="bank_code" id="bankCode">
						  <option value="044">Access Bank Nigeria Plc</option>
						  <option value="063">Diamond Bank Plc</option>
						  <option value="050">Ecobank Nigeria</option>
						  <option value="070">Fidelity Bank Plc</option>
						  <option value="011">First Bank of Nigeria Plc</option>
						  <option value="244">First City Monument Bank</option>
						  <option value="058">Guaranty Trust Bank Plc</option>
						  <option value="030">Heritaage Banking Company Ltd</option>  
						  <option value="301">Jaiz Bank</option>  
						  <option value="082">Keystone Bank Ltd</option>  
						  <option value="039">Stanbic IBTC Plc</option>
						  <option value="232">Sterling Bank Plc</option> 
						  <option value="032">Union Bank Nigeria Plc</option>  
						  <option value="033">United Bank for Africa Plc</option>  
						  <option value="215">Unity Bank Plc</option>  
						  <option value="035">WEMA Bank Plc</option>  
						  <option value="057">Zenith Bank International</option>  
					  </select>
				 		<label>Account Number: </label> <input type="text" name="account_number" maxlength="10" pattern="\d{10}" title="Please enter exactly 10 digits" required />
				 		<div class="modal-footer">
				  	<p><input type="submit" value="Create Account" class="btn btn-sm btn-primary"></p>
                
            </div>
			    </form>
            </div>
            
        </div>
    </div>
</div>
	
<% end %>


<% if current_user.fan_role? %>
	<div class="header bg-primary pb-6">
	  <div class="container-fluid">
	    
	  </div>
	</div>
	<!-- Page content -->
	<div class="container-fluid mt--6">
	  <div class="row">
	    <div class="col">
	      <%= render 'pages/tables/light' %>
	    </div>
	  </div>
	</div>
<% end %>

<% if current_user.superadmin_role? %>
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <%= render partial: 'pages/header', locals: {
            icon: 'home',
            breadcrumb_1: 'Dashboards',
            breadcrumb_2: 'Home'
      } %>
      <%= render 'pages/dashboard/metrics_summary' %>
    </div>
  </div>
</div>
<div class="container-fluid mt--6">
  <div class="row">
  </div>
  <div class="row">
    <div class="col-xl-8">
      <%= render 'pages/dashboard/tables/page_visits' %>
    </div>
    
  </div>
</div>
<% end %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>

<script type="text/javascript">

// when DOM is ready
$(document).ready(function () {

     // Attach Button click event listener 
    $("#myBtn").click(function(){

         // show Modal
         $('#myModal').modal('show');
         $('.modal-backdrop').remove();
    });
});

</script>

 

app/views/layouts/application.html.erb
<!--
=========================================================
* Argon Dashboard - v1.2.0
=========================================================
* Product Page: https://www.creative-tim.com/product/argon-dashboard


* Copyright  Creative Tim (http://www.creative-tim.com)
* Coded by www.creative-tim.com



=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html>
  <%= render 'shared/head' %>
  <% if notice %>
  	<p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  	<p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</html>

app/views/pages/_footer.html.erb
<footer class="footer pt-0">
  <div class="row align-items-center justify-content-lg-between">
    <div class="col-lg-6">
      <div class="copyright text-center  text-lg-left  text-muted">
        &copy; 2020 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
      </div>
    </div>
    <div class="col-lg-6">
      <ul class="nav nav-footer justify-content-center justify-content-lg-end">
        <li class="nav-item">
          <a href="https://www.creative-tim.com" class="nav-link" target="_blank">MuzikHub</a>
        </li>
        <li class="nav-item">
          <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
        </li>
        <li class="nav-item">
          <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
        </li>
        <li class="nav-item">
          <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/pages/_header.html.erb
<div class="row align-items-center py-4">
  <div class="col-lg-6 col-7">
    <h6 class="h2 text-white d-inline-block mb-0"><%= breadcrumb_2 %></h6>
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
      <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
        <li class="breadcrumb-item"><a href="#"><%= fa_icon icon %></i></a></li>
        <li class="breadcrumb-item"><a href="#"><%= breadcrumb_1 %></a></li>
        <li class="breadcrumb-item active" aria-current="page"><%= breadcrumb_2 %></li>
      </ol>
    </nav>
  </div>
</div>

app/views/pages/dashboard/_metrics_summary.html.erb
<div class="row">
  <div class="col-xl-3 col-md-6">
    <div class="card card-stats">
      <!-- Card body -->
      <div class="card-body">
        <div class="row">
          <div class="col">
            <h5 class="card-title text-uppercase text-muted mb-0">Total Revenue</h5>
            <span class="h2 font-weight-bold mb-0">N<%= sprintf('%.2f', @total_revenue.to_f/100) %></span>
          </div>
          <div class="col-auto">
            <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
              <i class="ni ni-active-40"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6">
    <div class="card card-stats">
      <!-- Card body -->
      <div class="card-body">
        <div class="row">
          <div class="col">
            <h5 class="card-title text-uppercase text-muted mb-0">Total Payout</h5>
            <span class="h2 font-weight-bold mb-0">N<%= sprintf('%.2f', @total_creator_payout.to_f/100) %></span>
          </div>
          <div class="col-auto">
            <div class="icon icon-shape bg-gradient-orange text-white rounded-circle shadow">
              <i class="ni ni-chart-pie-35"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6">
    <div class="card card-stats">
      <!-- Card body -->
      <div class="card-body">
        <div class="row">
          <div class="col">
            <h5 class="card-title text-uppercase text-muted mb-0">Total Payment</h5>
            <span class="h2 font-weight-bold mb-0">N<%= sprintf('%.2f', @total_payment.to_f/100) %></span>
          </div>
          <div class="col-auto">
            <div class="icon icon-shape bg-gradient-green text-white rounded-circle shadow">
              <i class="ni ni-money-coins"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard/tables/_page_visits.html.erb
<div class="card">
  <div class="card-header border-0">
    <div class="row align-items-center">
      <div class="col">
        <h3 class="mb-0">Transactions</h3>
      </div>
    </div>
  </div>
  <div class="table-responsive">
    <!-- Projects table -->
    <% if @transactions %>
        <table class="table align-items-center table-flush">
          <thead class="thead-light">
            <tr>
              <th scope="col">Artist</th>
              <th scope="col">Music Title</th>
              <th scope="col">Amount Paid</th>
              <th scope="col">Staus</th>
              <th scope="col">Artist Payout</th>
              <th scope="col">Revenue</th>
            </tr>
          </thead>
          <tbody>
            <% @transactions.each do |transaction|%>
            <tr>
              <th scope="row">
                <%= transaction.song_name[0]['artist'] %>
              </th>
              <td>
                <%= transaction.song_name[0]['title'] %>
              </td>
              <td>
                N<%= sprintf('%.2f', transaction.amount.to_f/100) %>
              </td>
              <td>
                <%= transaction.status.upcase %>
              </td>
              <td>
                N<%= sprintf('%.2f', transaction.creator_amount.to_f/100) %>

              </td>
              <td>
                N<%= sprintf('%.2f', transaction.platform_amount.to_f/100) %>                
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
      </div>
    </div>

app/views/pages/logged_out/_footer.html.erb
<footer class="py-5" id="footer-main">
  <div class="container">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-6">
        <div class="copyright text-center text-xl-left text-muted">
          &copy; 2021 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">MuzikHub</a>
        </div>
      </div>
      <div class="col-xl-6">
        <ul class="nav nav-footer justify-content-center justify-content-xl-end">
          <li class="nav-item">
            <a href="https://www.creative-tim.com" class="nav-link" target="_blank">MuzikHub</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
          </li>
          <li class="nav-item">
            <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
          </li>
          <li class="nav-item">
            <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank"></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/pages/logged_out/_topnav.html.erb
<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <a href="dashboard.html">
              <%= image_tag 'brand/blue.png' %>
            </a>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
        
        <li class="nav-item">
          <a href="<%= pages_login_path %>" class="nav-link">
            <span class="nav-link-inner--text">Login</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="<%= pages_register_path %>" class="nav-link">
            <span class="nav-link-inner--text">Register</span>
          </a>
        </li>
      </ul>
      <hr class="d-lg-none" />
      <ul class="navbar-nav align-items-lg-center ml-lg-auto">
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://www.facebook.com/creativetim" target="_blank" data-toggle="tooltip" data-original-title="Like us on Facebook">
            <%= fa_icon 'facebook' %>
            <span class="nav-link-inner--text d-lg-none">Facebook</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://www.instagram.com/creativetimofficial" target="_blank" data-toggle="tooltip" data-original-title="Follow us on Instagram">
            <%= fa_icon 'instagram' %>
            <span class="nav-link-inner--text d-lg-none">Instagram</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://twitter.com/creativetim" target="_blank" data-toggle="tooltip" data-original-title="Follow us on Twitter">
            <%= fa_icon 'twitter' %>
            <span class="nav-link-inner--text d-lg-none">Twitter</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://github.com/creativetimofficial" target="_blank" data-toggle="tooltip" data-original-title="Star us on Github">
            <%= fa_icon 'github' %>
            <span class="nav-link-inner--text d-lg-none">Github</span>
          </a>
        </li>
        
      </ul>
    </div>
  </div>
</nav>

app/views/pages/login.html.erb
<% content_for(:title) { 'Welcome to MuzikHub!' } %>
<% content_for(:subtitle) { 'Join the fastest growing music platform in the world.' } %>

<div class="container mt--8 pb-5">
  <div class="row justify-content-center">
    <div class="col-lg-5 col-md-7">
      <div class="card bg-secondary border-0 mb-0">
        <div class="card-header bg-transparent pb-5">
          <div class="text-muted text-center mt-2 mb-3"><small>Sign in with</small></div>
          <div class="btn-wrapper text-center">
            <a href="#" class="btn btn-neutral btn-icon">
              <span class="btn-inner--icon"><%= image_tag 'icons/common/github.svg' %></span>
              <span class="btn-inner--text">Github</span>
            </a>
            <a href="#" class="btn btn-neutral btn-icon">
              <span class="btn-inner--icon"><%= image_tag 'icons/common/google.svg' %></span>
              <span class="btn-inner--text">Google</span>
            </a>
          </div>
        </div>
        <div class="card-body px-lg-5 py-lg-5">
          <div class="text-center text-muted mb-4">
            <small>Or sign in with credentials</small>
          </div>
          <form role="form">
            <div class="form-group mb-3">
              <div class="input-group input-group-merge input-group-alternative">
                <div class="input-group-prepend">
                  <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                </div>
                <input class="form-control" placeholder="Email" type="email">
              </div>
            </div>
            <div class="form-group">
              <div class="input-group input-group-merge input-group-alternative">
                <div class="input-group-prepend">
                  <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                </div>
                <input class="form-control" placeholder="Password" type="password">
              </div>
            </div>
            <div class="custom-control custom-control-alternative custom-checkbox">
              <input class="custom-control-input" id=" customCheckLogin" type="checkbox">
              <label class="custom-control-label" for=" customCheckLogin">
                <span class="text-muted">Remember me</span>
              </label>
            </div>
            <div class="text-center">
              <button type="button" class="btn btn-primary my-4">Sign in</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col-6">
          <a href="#" class="text-light"><small>Forgot password?</small></a>
        </div>
        <div class="col-6 text-right">
          <a href="#" class="text-light"><small>Create new account</small></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/user_transaction.html.erb
 <div class="col-4 text-right">
	    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

 </div>
 <h6 class="heading-small text-muted mb-4">My Trasanctions</h6>
	      <% if @user_transactions %>

		      	<table data-toggle="table" class="table table-responsive">
				    <thead>
				        <tr>
				            <th data-field="name" data-sortable="true">Transaction Reference</th>
				            <th data-field="label" data-sortable="true">Amount(Naira)</th>
				            <th data-field="title" data-sortable="true">Status</th>
				            <th data-field="price" data-sortable="true">Payment Date</th>
				            <th data-field="accept-job" data-sortable="true">Song Title</th>
				        </tr>
				     </thead>
		     		<tbody>
		     			<% @user_transactions.each do |trxn| %>
				         <tr>
				             <td><%= trxn.trxn_reference %></td>
				             <td><%= sprintf('%.2f', trxn.amount.to_f/100) %></td>
				             <td><%= trxn.status %></td>
				             <td><%= trxn.payment_date %></td>
				             <td>Yes and Amen</td>

				         </tr>
				        <% end %>
		    		</tbody>
		    	 </table>
		      <% end %>
	      <div class="pl-lg-4">
	      </div>